# Generated by Django 2.1.4 on 2018-12-15 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mails',
            name='gehort_user',
        ),
        migrations.AddField(
            model_name='mails',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
