# Generated by Django 2.1.4 on 2018-12-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mailapi', '0002_auto_20181215_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='objekt',
            field=models.CharField(default='Kein Object.', max_length=120),
        ),
    ]
