# Generated by Django 2.1.4 on 2018-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mailapi', '0004_auto_20181216_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='objekt',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
